/*
 * Application_Init.c
 *
 *  Created on: 04-Nov-2022
 *      Author: ESB203C
 */
#include "Filter.h"
#include "PID_controller.h"

#define NOTCH_NUM_COEFF_0 0.9901f
#define NOTCH_NUM_COEFF_1 -1.9801f
#define NOTCH_NUM_COEFF_2 0.9901f
#define NOTCH_DEN_COEFF_1 -1.9801f
#define NOTCH_DEN_COEFF_2 0.9802f

#define BP_NUM_COEFF_0 1.009f
#define BP_NUM_COEFF_1 -1.998f
#define BP_NUM_COEFF_2 0.989f
#define BP_DEN_COEFF_1 -1.9980f
#define BP_DEN_COEFF_2 0.9980f

#define PID_POS_CONTROL_KP 3700.0f
#define PID_POS_CONTROL_KI 500.0f
#define PID_POS_CONTROL_KD 300.0f
#define PID_POS_CONTROL_KAI 0.0f
#define PID_POS_CONTROL_TS 0.0002f
#define PID_POS_CONTROL_N 200.0f
#define PID_POS_CONTROL_ACC_LIMIT_P 25.0f
#define PID_POS_CONTROL_ACC_LIMIT_N -25.0f

#define PID_CUR_CONTROL_KP 3700.0f
#define PID_CUR_CONTROL_KI 500.0f
#define PID_CUR_CONTROL_KD 300.0f
#define PID_CUR_CONTROL_KAI 0.0f
#define PID_CUR_CONTROL_TS 0.0002f
#define PID_CUR_CONTROL_N 200.0f
#define PID_CUR_CONTROL_ACC_LIMIT_P 25.0f
#define PID_CUR_CONTROL_ACC_LIMIT_N -25.0f

void Application_Init(void)
{
    ASW_IIR_second_order_init(&Filter_Notch, NOTCH_NUM_COEFF_0,NOTCH_NUM_COEFF_1, NOTCH_NUM_COEFF_2, NOTCH_DEN_COEFF_1, NOTCH_DEN_COEFF_2);
    ASW_IIR_second_order_init(&Filter_BP, BP_NUM_COEFF_0,BP_NUM_COEFF_1, BP_NUM_COEFF_2, BP_DEN_COEFF_1, BP_DEN_COEFF_2);
    Initialise_PID(&PID_Position_Control, PID_POS_CONTROL_KP, PID_POS_CONTROL_KI, PID_POS_CONTROL_KD,  PID_POS_CONTROL_KAI, PID_POS_CONTROL_N, PID_POS_CONTROL_ACC_LIMIT_P, PID_POS_CONTROL_ACC_LIMIT_N  , PID_POS_CONTROL_TS);
    Initialise_PID(&PID_Current_Control, PID_CUR_CONTROL_KP, PID_CUR_CONTROL_KI, PID_CUR_CONTROL_KD,  PID_CUR_CONTROL_KAI, PID_CUR_CONTROL_N, PID_CUR_CONTROL_ACC_LIMIT_P, PID_CUR_CONTROL_ACC_LIMIT_N  , PID_CUR_CONTROL_TS);
}


